
    var arrLang = {
      'en': {
        'home': 'Home',
        'aboutt':'About',
        'documents':'Documents',
        'Member' :'Members',
        'news' :'News',
        'contact':'Contact',
        'Open':'Open Government Partnership Kosova Initiative.',
        'Check':'Check the OGP Process Milestones',
        'Aligibilityt':'Eligibility Criteria and Pass the Values Check',
        'Ministry':'Ministry of Local Government Administration',
        'Submitting':'Submitting the Letter of Intent',
        'Engaging':'Engaging Civil Society Organizations',
        'Submittingg':'Submitting the National Action Plan.',
        'ABOUT':'ABOUT', 
        'Kosovo':'The Kosovo government in its meeting on 9 July 2013 took ​​a decision to initiate the procedures for membership of the Republic of Kosovo in the multinational initiative',
        'Kosovo1':'The decision obliged the Government of Kosovo to implement all obligations required under the OGP membership.As such, the Government of Kosovo with the appointed lead Ministry of European Integration submitted all the necessary documents back in 2013 to become part of the initiative.',
        'Unfortunately':'Unfortunately, the Kosovo government received the notification letter that it cannot be part of the initiative. Ever since, the Republic of Kosovo has committed to the principles of open and accountable government, and continued its attempts to put Kosovo in the digital governance realm.',
        'With':'With the adoption of the National Open Data Charter, the E-Kosova state portal, public consultation platforms, public service digitalisation, e-participation platform, state budget transparency tools and many more, the Kosovo government believes it now possesses the necessary principles to be part of the OGP. On 8 June 2021 the government of Kosovo once again took the decision to begin the initiative for membership at the OGP.',
        'The' :'The lead Ministry appointed to coordinate and foster the national initiative is the Ministry of Local Government Administration. The National Action Plan will cover the period of 2022-2024 and will provide concrete feasible action items that aim at increasing governmental transparency, all while including the civil society organizations as main catalysts of the initiative.',
        'This' :'This website provides all important documents and other relevant information regarding the Republic of Kosovo and its second attempt to become part of the OGP. Everyone is encouraged to provide their comments regarding the initiative so that the process is transparent and reflects the opinions of the citizens of the Republic of Kosovo.',
        'IMPORTANT':'IMPORTANT DOCUMENTS',
        'ogp' :'OGP Kosova Budget',
        'Letter':'Letter of Intent',
        'OGD':'Open Government Declaration',
        'nap':'National Action Plan',
        'DGK':'Decisions from theGovernment of Kosovo',
        'moduls':'There are no attachments yet uploaded by the admin panel for this box, please try again in the following period.',
        'NATIONAL':'OGP NATIONAL COORDINATING COMMITTEE',
        'last':'Last Post',
        'title':'Inauguration of the National Coordinating Committee as part of the Open Government Partnership – OGP',
        'description':'-29 October, 2021 - Members of the National Coordination Committee, representatives of public institutions and civil society, Members of the National Coordination Committee, representatives of public institutions and civil society, will play a key role in drafting the National Action Plan 2022-2024 for Kosovo within the Open Government Partnership (OGP)',
        'read':'Read More',
        'Ex':'Ex Rilindja building Floors: 11, 12 and 13 Pristina, Republic of Kosovo',
        'phone':'Phone',
        'email':'Email',
        'Copy':'© Copyright 2021 Open Data Kosovo. All Rights Reserved.',
        'min': 'In order to coordinate the membership process of the Republic of Kosovo in the Open Government Partnership – OGP, it is held the information session with the representatives from the civil society. ',
        'min2':'The Chairman of the National Coordination Committee for the Drafting of the National Action Plan within the OGP, Mr. Fidan Kalaja, presented the perspective of the Government of Kosovo about the process of membership of Kosovo in the OGP, mentioning some of the challenges and difficulties that have been identified during Kosovos journey for membership in the OGP. Also Mr. Kalaja mentioned the importance of cooperation between the government and civil society, focusing on the actions and decisions that are foreseen to be taken during this process.',
        'min3':'The Director of CIVIKOS Mrs. Donika Emini, during her presentation, explanined the importance of cooperation between stakeholders engaged in the OGP process and the role of civil society in an open and accountable governance.',
        'min4':'During this discussion, as part of the panel Mr. Denion Galimuna, the Coordinator of KFOS programmes, mentioned the history of cooperation of KFOS with government representatives, while focusing on Open Data and the importance of transparency in open governments.  Additionally, Mr. Galimuna mentioned the main challenges from the past and the steps that need to be followed in the future in order to avoid difficulties and have better results in data processing and publication.',
        'min5':'Whereas the representative of BIRN Mr. Kreshnik Gashi, explained the importance of media in the increase of transparency and accountability, while emphasizing that public documents should be accessible and in service to citizens. While providing some examples from the past Mr. Gashi explained the main media difficulties in regards to cooperation with the institutions or government bodies, but focusing on the next steps for increasing transparency and accountability. ',
        'min6':'At the end, Mrs. Paulina Behluli, Project Coordinator from Open Data Kosovo, explained the objectives of the ODK initiative, while mentioning the results achieved and the future projects.',
        'new1':'Today it is held the inauguration ceremony of the National Coordinating Committee as part of the Open Government Partnership – OGP. During this inauguration there were present the Prime Minister of the Republic of Kosovo Mr. Albin Kurti, the Minister of Local Government Administration Mr. Elbert Krasniqi, the Head of OGP in Kosovo Mr. Fidan Kalaja, government representatives as well as representatives from civil society organizations',
        'new2':'The Prime Minister of the Republic of Kosovo Mr. Albin Kurti in his speech emphasized the importance of inclusion of civil society organization in government processes, while mentioning the case of OGP, as one of the subjects where there is a need for a complete and continuous coordination between the government and civil society organizations. “I am delighted to see so many civil society leaders, women and men defending equality, opportunity, activity and freedom every day. And it is not always easy to do this, because throughout history, progress has always been driven by those who have the courage to raise their voice and think not only what the current situation is, but what may be important for the future, and that they are determined to work in order to bring the change that they are seeking”.',
        'new3':'Minister of Local Government Administration Mr. Elbert Krasniqi, mentioned the importance of the Republic of Kosovo to become a member of OGP. “There are a number of benefits with the membership of the Republic of Kosovo in the Open Government Partnership. First, the Republic of Kosovo would benefit by being a member as an independent state, in an international mechanism which is also a priority of Government of Kosovo. Second, would enable the application of the principle of radical transparency in the governance of the Kurti II Government. It would structure cooperation with civil society organizations and the business sector. Most importantly, open and transparent governance is a prerequisite for fighting corruption within public institutions. By fighting corruption, our country becomes an attractive and safe place for private investment from outside and inside Kosovo. With this membership, the Republic of Kosovo will become part of the countries with developed democracies which promote transparent governance and which would affect the reform and efficiency of public services.” ',
        'new4':'Additionally, the representatives from Civil Society Organizations, have praised the government’s willingness to cooperate with civil society organizations, while showing full support thought the whole process.The process of OGP in the Republic of Kosovo, is considered a priority of Ministry of Local Government Administration, due to the fact that the organizations is established by government representatives and civil society in order to have open and transparent governance, citizen participation in decision-making, inclusiveness and accountable governance in order to improve public policies and services.'

        
        
      },
      'sq': {
        'home': 'Faqja Kryesore',
        'aboutt': 'Rreth Nesh',
        'documents':'Dokumentet',
        'Member':'Anëtar',
        'news':'Lajme',
        'contact':'Kontakti',
        'Open':'Iniciativa për Partneritet të Hapur të Qeverisë të Kosovës .',
        'Check':'Kontrolloni arritjet e procesit OGP',
        'Aligibilityt':'Pranueshmëria e Kritereve dhe Kontrolli i Vlerave Kalimtare',
        'Ministry':'Ministria e Administrimit të Pushtetit Lokal',
        'Submitting':'Dorëzimi i Letrës të Rekomandimit',
        'Engaging':'Angazhimi i Organizatave të Shoqërisë Civile',
        'Submittingg':'Dorëzimi i Planit Kombëtar të Veprimit.',
        'ABOUT':'RRETH PLATFORMËS',
        'Kosovo':'Qeveria e Kosovës në mbledhjen e saj më 9 korrik 2013 mori një vendim për fillimin e procedurave për anëtarësimin e Republikës së Kosovës në nismën shumëkombëshe ',
        'Kosovo1':'Vendimi e obligoi Qeverinë e Kosovës të zbatojë të gjitha obligimet e kërkuara për anëtarësim në OGP. Si e tillë, Qeveria e Kosovës me Ministrinë udhëheqëse të emëruar të Integrimit Evropian dorëzoi të gjitha dokumentet e nevojshme në vitin 2013 për tu bërë pjesë e nismës.',
        'Unfortunately':'Fatkeqësisht, qeveria e Kosovës pranoi letrën e njoftimit se nuk mund të jetë pjesë e nismës. Që atëherë, Republika e Kosovës është përkushtuar ndaj parimeve të qeverisjes së hapur dhe të përgjegjshme, dhe ka vazhduar përpjekjet e saj për ta vënë Kosovën në sferën e qeverisjes dixhitale.',
        'With':'Me miratimin e Kartës Kombëtare të të Dhënave të Hapura, portalit shtetëror E-Kosova, platformave të konsultimit publik, dixhitalizimit të shërbimeve publike, platformës së pjesëmarrjes elektronike, mjeteve të transparencës së buxhetit të shtetit dhe shumë më tepër, qeveria e Kosovës beson se tani posedon parimet e nevojshme për të qenë pjesë e PQH-së. Më 8 qershor 2021 qeveria e Kosovës edhe një herë mori vendimin për të filluar iniciativën për anëtarësim në OGP.',
        'The' :'Ministria udhëheqëse e emëruar për të koordinuar dhe nxitur nismën kombëtare është Ministria e Administrimit të Pushtetit Lokal. Plani Kombëtar i Veprimit do të mbulojë periudhën 2022-2024 dhe do të sigurojë artikuj konkretë të mundshëm veprimi që synojnë rritjen e transparencës qeveritare, duke përfshirë të gjitha organizatat e shoqërisë civile si katalizatorët kryesorë të nismës.',
        'This' :'Kjo faqe e internetit ofron të gjitha dokumentet e rëndësishme dhe informata të tjera përkatëse në lidhje me Republikën e Kosovës dhe përpjekjen e saj të dytë për tu bërë pjesë e PQH-së. Të gjithë inkurajohen të japin komentet e tyre lidhur me nismën në mënyrë që procesi të jetë transparent dhe të pasqyrojë opinionet e qytetarëve të Republikës së Kosovës.',
        'IMPORTANT':'DOKUMENTET E RËNDËSISHME',
        'ogp' :'OGP Buxheti i Kosovës',
        'Letter':'Letër Rekomandimi',
        'OGD':'Deklarata e Qeverisë së Hapur',
        'nap':'Plani Kombëtar i Veprimit',
        'DGK':'Vendimet e Qeverisë së Kosovës',
        'moduls':'Nuk ka të bashkëngjitur apo të ngarkuar asgjë nga ana e panelit administratues për këtë kuti, ju lutemi provoni përsëri në periudhën vijuese.',
        'NATIONAL':'OGP NATIONAL COORDINATING COMMITTEE',
        'last':'Postimi i fundit',
        'title':'Inaugurimi i Komitetit Nacional Koordinues në kuadër të Open Government Partnership – OGP',
        'description':'-29 Tetor, 2021- Anëtarët e Komitetit Kombëtar të Koordinimit, përfaqësues të institucioneve publike dhe shoqërisë civile, anëtarë të Komitetit Kombëtar të Koordinimit, përfaqësues të institucioneve publike dhe shoqërisë civile, do të luajnë një rol kyç në hartimin e Planit Kombëtar të Veprimit 2022-2024. për Kosovën në kuadër të Partneritetit për Qeverisje të Hapur (OGP)',
        'read':'Lexo më shumë',
        'Ex':'Ndërtesa e Ish Rilindjes, Katet: 11, 12 dhe 13, Prishtinë, Republika e Kosovës',
        'phone':'Telefoni',
        'email':'Email',
        'Copy':'©E drejta e autorit Open Data Kosovo. Të gjitha të drejtat e rezervuara',
        'min':'Me qëllim të koordinimit për procesin e anëtarësimit të Republikës së Kosovë në Open Government Partnership - OGP, është mbajtur sesioni informues me përfaqësues nga shoqëria civile.',
        'min2':'Udhëheqësi i Komitetit Nacional Koordinues për Hartimin e Planit Nacional të Veprimit në kuadër të OGP-së, z. Fidan Kalaja, paraqiti prespektivën e qeverisë së Kosovës rreth procesit të hartimit të Kosovës në OGP, duke përmendur disa nga sfidat dhe vështirësit të cilat janë evidentuar gjatë rrugëtimit të Kosovës për anëtarësim në OGP. Gjithashtu z. Kalaja përmendi rëndësinë e bashkëpunimit në mes të qeverisë dhe shoqërisë civile duke u fokusuar në veprimet dhe vendimet të cilat janë paraparë të merrën gjatë këtij procesi.',
        'min3':'Drejtoresha e CIVIKOS znj. Donika Emini, gjatë prezantimit të saj, shpjegoi rëndësinë e bashkëpunimit në mes të akterëve të përfshirë në procesin e OGP-së dhe rolin e shoqërisë civile në qeverisjen e hapur dhe llogaridhënëse.',
        'min4':'Gjatë këtij diskutimi si panelist, z. Denion Galimuna, Koordinator i programeve të KFOS-it, përmendi historikun e bashkëpunimit të KFOS-it me përfaqësues qeveritar, duke u fokusuar tek Open Data dhe rëndësia e transparencës në qeveritë e hapura. Gjithashtu, z. Galimuna përmendi sfidat kryesore nga e kaluara dhe hapat të cilat duhet të ndiqen në të ardhmen që të mënjanohen vështirësitë dhe të ketë rezultate më të mira në procesimin dhe publikimin e të dhënave.',
        'min5':'Ndërkaq përfaqësuesi i BIRN, z. Kreshnik Gashi, shpjegoi rëndësinë e mediave në rritjen e transparencës dhe llogaridhënies duke theksuar se dokumentat publike duhet të jenë të qasshme dhe në shërbim të qytetarëve. Duke ofruar disa shembuj nga e kaluara z. Gashi shpjegoi vështërsitë kryesore të medias në bashkëpunim me institucionet apo organet qeveritare duke u fokusuar tek hapat e ardhshëm në shërbim të rritjes së transparencës dhe llogaridhënies.',
        'min6':'Në fund, znj. Paulina Behluli, Koordinatore e Projekteve nga Open Data Kosova, sqaroi objektivat e iniciativës së ODK-së duke përfshirë rezultatet e arritura dhe projektet për të ardhmen.',
        'new1':'Sot, është zhvilluar ceremomia e inagurimit të Komitetit Nacional Koordinues në kuadër të Open Government Partnership – OGP. Gjatë këtij inagurimi të pranishëm ishin Kryeministri i Republikës së Kosovës z. Albin Kurti, Ministri i Administrimit të Pushtetit Lokal z. Elbert Krasniqi, Udhëheqësi i OGP Kosovës z. Fidan Kalaja, përfaqësues qeveritar si dhe përfaqësues nga organizatat e shoqërisë civile.',
        'new2':'Kryeministri i Republikës së Kosovës, z. Albin Kurti, në fjalën e tij, theksoi rëndësinë e përfshirjës së organizatave të shoqërisë civile në proceset qeveritare, duke përmendur rastin e OGP-së, si një nga temat në të cilat duhet koordinim i plotë dhe i vazhdueshëm në mes të qeverisë dhe organizatave të shoqërisë civile. “Jam i kënaqur kur shoh kaq shumë udhëheqës nga shoqëria civile, gra dhe burra që mbrojnë barazinë, mundësitë, drejtësinë dhe lirinë çdo ditë. Dhe nuk është gjithmonë e lehtë për të bërë këtë, sepse gjatë historisë, përparimi është nxitur gjithmonë nga qytetarët që kanë guximin të ngrenë zërin e tyre dhe të mendojnë jo vetëm atë që është aktuale, por çfarë mund të jetë e rëndësishme për të ardhmen, dhe që janë të gatshëm të punojnë për të sjellë ndryshimin që ata kërkojnë.”',
        'new3':'Ministri i Administrimit të Pushtetit Lokal, z. Elbert Krasniqi, përmendi rëndësinë e anëtarsimit të Republikës së Kosovës në OGP. “Ekzistojnë një sërë përfitimesh me anëtarësimin e Republikës së Kosovës në Partneritetin për Qeverisje të Hapur. E para Republika e Kosovës do të përfitonte anëtarësim si shtet i pavarur në një mekanizëm ndërkombëtar që është edhe prioritet i Qeverisë së Kosovës. E dyta do të mundësonte zbatimin e parimit për transparencë radikale në qeverisjen e Qeverisë Kurti II. Do të strukturonte bashkëpunimin me organizatat e shoqërisë civile dhe sektorin e biznesit. Më e rëndësishmja është se qeverisja e hapur dhe transparente është parakusht për luftimin e korrupsionit brenda institucioneve publike. Me luftimin e korrupsionit vendi ynë bëhet vend atraktiv dhe i sigurt për investime private nga jashtë dhe brenda Kosovës. Më këtë anëtarësim Republika e Kosovës do të bëhet pjesë e vendeve me demokraci të zhvilluar e cila promovon qeverisje transparente dhe që do të ndikonte në reformimin dhe efikasitetin e shërbimeve publike”. ',
        'new4':'Gjithashtu, përfaqësues nga Organizatat e Shoqërisë Civile, vlerësuan lartë gatishmërinë e qeverisë për bashkëpunim me organizatat e shoqërisë civile, duke treguar mbështetje të plotë përgjatë gjithë procesit.Procesi i OGP-së për Republikën e Kosovës, konsiderohet prioritet i Ministrisë së Administrimit të Pushtetit Lokal, për arsye të profilit të organizatës e cila është krijuar nga përfaqësues qeveritar dhe shoqërisë civile në mënyrë që të ketë qeverisje të hapur e  transparente, pjesëmarrje të qytetarëve në vendimmarrje, gjithpërfshirje dhe qeverisje llogaridhënëse me qëllim të përmirësimit të politikave dhe shëbimeve publike.'
        
        
        
      },
      'srb' :{
          'home':'Glavn stranica',
          'aboutt':'O platformi',
          'documents':'Dokumenti',
          'Member':'Član',
          'news' :'Vesti',
          'contact':'Kontakt',
          'Open':'Inicijativa za Otvoreno Vlade Kosova .',
          'Check':'Proverite prekretnice OGP procesa',
          'Aligibilityt':'Kriterijumi Podobnosti i Kontrola Prolazne Vrednosti',
          'Ministry':'Ministarstvo Administracije Lokalne Samouprave',
          'Submitting':'Podnošenje Preporučnog Pisma',
          'Engaging':'Angažovanje Organizacija Civilnog Društva',
          'Submittingg':'Podnošenje Nacionalnog Akcionog Plana.',
          'ABOUT':'O PLATFORMI',
          'Kosovo':'Vlada Kosova je na svom sastanku 9. jula 2013. godine donela odluku o okončanju procedura za članstvo Republike Kosovo u multinacionalnom pokretu ',
          'Kosovo1':' Odluka je obavezala Vladu Kosova da sprovede sve obaveze koje su potrebne prema članstvu u OPV -u. Kao takav, Vlada Kosova sa imenovanim Ministarstvom za Evropske Integracije od 2013. godine.',
          'Unfortunately':'Nažalost, vlada Kosova primila je pismo obaveštenja da ne može biti deo inicijative. Od tada je Republika Kosovo usvojila principe otvorenog i odgovornog pristupa i da se Kosovo stavi u oblast digitalnog upravljanja.',
          'With':'Usvajanjem Nacionalne Povelje o otvorenim podacima, državnog portala E-Kosovo, platformi za javne konsultacije, digitalizacije javnih usluga, platforme za e-učešće, sredstava za transparentnost državnog budžeta i mnogih drugih, vlada Kosova veruje da sada poseduje neophodne principe deo OGP -a. Vlada Kosova je 8. juna 2021. godine ponovo donela odluku o pokretanju inicijative za članstvo u OPV.',
          'The':'Vodeće Ministarstvo imenovan za koordinaciju i podsticanje nacionalne inicijative je Ministarstvo Lokalne Uprave. Nacionalni Akcioni Plan pokrivaće period od 2022. do 2024. godine i daće konkretne izvodljive stavke delovanja koje imaju za cilj povećanje transparentnosti vlade, a sve organizacije civilnog društva uključuju kao glavne katalizatore inicijative.',
          'This':'Ova veb stranica pruža sve važne dokumente i druge relevantne informacije o Republici Kosovo i njenom drugom pokušaju da postane deo OPV -a. Pozivaju se svi da daju svoje komentare u vezi sa inicijativom kako bi proces bio transparentan i odražavao mišljenja građana Republike Kosovo.',
          'IMPORTANT':'VAŽNI DOKUMENTI',
          'ogp':'OGP Kosovski Budžet',
          'Letter':'Pismo Preporuke',
          'OGD':'Otvorena Deklaracija o Vladi',
          'nap':'Nacionalni Akcioni Plan',
          'DGK':'Odluke Vlade Kosova',
          'moduls':'Nema ničega priloženo ili otpremljeno za ovu kutiju od strane administratorskog panela, pokušajte ponovo kasnije.',
          'NATIONAL':'OGP NATIONAL COORDINATING COMMITTEE',
          'last':'Poslednja objava',
          'title':'Inaugurisanje Nacionalnog koordinanacionog odbora u okviru “ Open Government Partnership – OGP”',
          'description':'-29. oktobar 2021. - Članovi Nacionalnog koordinacionog odbora, predstavnici javnih institucija i civilnog društva, članovi Nacionalnog koordinacionog odbora, predstavnici javnih institucija i civilnog društva, imaće ključnu ulogu u izradi Nacionalnog akcionog plana 2022-2024. za Kosovo u okviru Partnerstva za otvorenu vlast (OGP)',
          'read':'Opširnije',
          'Ex':'Bivša zgrada Rilindja, Spratovi: 11, 12 i 13, Priština, Republika Kosovo',
          'phone':'Telefon',
          'email':'Email:',
          'Copy':'©Autorsko Pravo Open Data Kosovos. Sva Prava Zadržana',
          'min':'U cilju koordinisanja procesa za učlanjivanje Republike Kosovo u Partnerstvu za otvorenu vladu - OGP, održana je informativna sesija sa predstavnicima civilnog društva.',
          'min2':'Rukovodilac Nacionalnog koordinacionog odbora za izradu  Nacionalnog plana delovanja u okviru OGP-a g. Fidan Kalaja, predstavio je perspektivu Vlade Kosova oko procesa učlanjivanja  Kosova u OGP-u, naznačujući nekoliko od izazova i poteškoća koji su evidentirani tokom putovanja Kosova ka učlanjivanju u  OGP-u. Takođe, g. Kalaja je istakao i značaj saradnje između Vlade i civilnog društva, fokusirajući se na aktivnostima i odlukama koje su predviđene da se preduzmu tokom ovog procesa.',
          'min3':'Direktorka  CIVIKOS-a gđa. Donika Emini, tokom prezentacije, objasnila je značaj saradnje između uključenih aktera u procesu OGP-a i ulogu civilnog društva u otvorenoj i odgovornoj vladi.',
          'min4':'Tokom rasprave kao panelista g. Denion Galimuna, koordinator  programa KFOS-a, govorio je o istorijatu saradnje  KFOS-a sa vladinim predstavnicima, fokusirajući se na “Open Data” i značaju transparetnosti u otvorenim vladama. Takođe, g. Galimuna, istakao je i o ključnim izazovima iz prošlosti i mere koje treba da se prate u budućem kako bi eliminisali poteškoće i  radi postizanja boljih rezultata u procesiranju i objavljivanju podataka.',
          'min5':'U međuvremenu, predstavnik BIRN-a, g. Kreshnik Gashi objasnio je značaj medija u povećanju transparentnosti i odgovornosti, ističući da bi javni dokumenti trebali biti dostupni i na usluzi građanima. Navodeći neke primere iz prošlosti g. Gashi je objasnio glavne poteškoće medija u saradnji sa vladinim institucijama ili telima, fokusirajući se na sledeće mere  u službi povećanja transparentnosti i odgovornosti.',
          'min6':'Na kraju gđa. Paulina Behluli, koordinator projekata iz “ Open Data Kosova”, objasnila ciljeve inicijative ODK-a uključujući postignute rezultate i projekte u budućem.',
          'new1':'Danas je održana svečanost inaugurisanja Nacionalnog koordinacionog odbora u okviru “Open Government Partnership – OGP”. Tokom ovog inaugurisanja prisutni su bili premijer Republike Kosovo g. Aljbin Kurti, ministar MALS-a Eljbert Krasnići, rukovodilac g. Fidan Kalaja, vladini predstavnici kao i predstavnici iz civilnog društva.',
          'new2':'Premijer Republike Kosovo g. Aljbin Kurti je u svom govoru istakao važnost uključivanja organizacija civilnog društva u vladine procese, navodeći slučaj OGP-a, kao jednu od tema u kojoj je potrebna puna i kontinuirana koordinacija između vlade i organizacija civilnog društva. „Drago mi je što vidim toliko lidera civilnog društva, žena i muškaraca koji svakodnevno brane jednakost, mogućnosti, pravdu i slobodu. To nije uvek lako učiniti, jer su kroz istoriju napredak uvek pokretali građani koji imaju hrabrosti da dignu glas i misle ne samo ono što je aktuelno, već ono što može biti važno za budućnost, i da su voljni da rade kako bi doveli do promene koju traže.”',
          'new3':'Ministar MALS-a  Eljbert Krasnići, napomenuo je značaj učlanjivanja Republike Kosovo u  OGP. "S učlanjivanjem Republike Kosovo u OGP, postoje niz koristi u parnerstvu za otvoreno vladanje. Kao prvo, Republika Kosovo će dobiti članstvo kao nezavisna država međunarodnog mehanizma, što je je ujedno i prioritet Vlade Republike  Kosovo. Drugo, omogučiće sprovođenje načela radikalne transpraetnosti u vladanju Vlade premijera Kurti II. Strukturiraće saradnju sa organizacijama civilnog društva i poslovnim sektorom.  Transparetna i otvorena Vlada kao zbačajan preduslov za borbu protiv korupcije unutar javnih institucija. S borbom protiv korupcije naša će zemlja biti bezbednija i atraktivnija za privatne investicije iz spolja i unutar Kosova. Sa ovim učlanjivanjem Republika Kosovo će biti deo razvijenih demokratskih država koja promoviše transparetno vladanje koja će imati uticaja na reformiranje i efikasnost javnih usluga.',
          'new4':'Takođe, predstavnici organizacija civilnog društva, visoko su cenili spremnost Vlade u saradnji sa organizacijama civilnog društva, pružajući potpunu podršku tokom celog procesa.Proces i OGP-a za Republiku Kosovo, smatra se se kao prioritet MALS-a, zbog  profila organizacije koja je stvorena od strane vladinih predstavnika i civilnog društva kako bi se postiglo otvotreno i transperetno vladanje, učešće građana u odlučivanju, sveobuhvatnost i odgovorno vladanje u cilju poboljšanja politika i javnih usluga.'
      }
    };

    // Process translation
    $(function() {
      $('.translate').click(function() {
        var lang = $(this).attr('id');

        $('.lang').each(function(index, item) {
          $(this).text(arrLang[lang][$(this).attr('key')]);
        });
      });
    });

